lsi: false
pygments: true
paginate: 1
permalink: /:title/
googleanalytics: UA-22599205-2
author:
  name: Robert Rhoades
  twitter: http://twitter.com/studioromeo
  google: https://plus.google.com/u/0/101733486307310199404
  lastfm: http://last.fm/user/studioromeo
  github: http://github.com/studioromeo